title: sanamorii
email: sanamorii@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I am perpetually sleepy
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jiansu.dev/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sanamorii

# Build settings
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
